nginx:
    container_name: xpblog_nginx
    image: nginx:1.10
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php72"
    volumes:
      - ~/opt/htdocs/html/:/usr/share/nginx/html/
      - ./nginx/vhosts/:/etc/nginx/conf.d/

php72:
    container_name: xpblog_php
    image: php:7.2
    tty: true
    volumes:
      - ~/opt/htdocs/html/:/usr/share/nginx/html/
      #- ~/opt/htdocs/html/docker-config/php/php72.ini:/usr/local/etc/php/php.ini
      - /etc/hosts:/etc/hosts