nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php7"
    volumes:
      - ~/opt:/opt
      - ./nginx/vhosts:/usr/local/nginx/conf/vhosts/

php7:
    image: php
    volumes:
      - ${DOCKER_OPT_PATH}:/opt
      - ${DOCKER_CODE_PATH}:/opt/htdocs
      - ./php/php-fpm:/usr/local/php/etc/php-fpm.d/
      - ./php/php-extension:/usr/local/php/etc/conf.d/
      - ./php/php7.ini:/usr/local/php/etc/php.ini
      - /etc/hosts:/etc/hosts
    env_file:
      - ./blog/env/blog/blog.env